application: college-main
version: 2
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static/css/bootstrap.min.css
  static_dir: static/css
  expiration: "30m"

- url: /static/js/jquery-1.11.1.min.js
  static_dir: static/js
  expiration: "30m"

- url: /static
  static_dir: static

- url: /login
  script: main.application
  secure: always

- url: /signup
  script: main.application
  secure: always

- url: /verify
  script: main.application
  secure: always

- url: /venmo-webhook
  script: main.application
  secure: always

- url: /recover
  script: main.application
  secure: always

- url: /.*
  script: main.application

libraries:
- name: jinja2
  version: latest

- name: PIL
  version: "1.1.7"

- name: ssl
  version: latest
